# Generated by Django 4.1 on 2023-03-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=55)),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('person', models.IntegerField()),
            ],
        ),
    ]
