# Generated by Django 4.1 on 2023-03-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMain', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addBooks',
            new_name='Books',
        ),
    ]
